{% set name = "pysd" %}
{% set version = "3.14.3" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysd-{{ version }}.tar.gz
  sha256: bc073a1d3bda1557455cfca9e0440ed41ae620cebc62b264a15ed1864df05c87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - black
    - chardet
    - lxml
    - numpy >=1.23
    - openpyxl >=3.1.2
    - pandas
    - parsimonious
    - portion
    - progressbar2
    - python >={{ python_min }}
    - regex
    - scipy
    - xarray >=2023.9
    - xlrd

test:
  imports:
    - pysd
    - pysd.cli
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/SDXorg/pysd
  summary: System Dynamics Modeling in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://pysd.readthedocs.io/
  dev_url: https://github.com/SDXorg/pysd

extra:
  recipe-maintainers:
    - enekomartinmartinez
    - JamesPHoughton
