{% set name = "pysd" %}
{% set version = "3.14.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysd-{{ version }}.tar.gz
  sha256: a81ade9c50b795e7b75fb8143b121959bc9f7ba94089f432b6b4fb2492c2d89b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - black
    - chardet
    - lxml
    - numpy >=1.23
    - openpyxl >=3.1
    - pandas
    - parsimonious
    - portion
    - progressbar2
    - python >=3.9
    - regex
    - scipy
    - xarray >=2023.09
    - xlrd

test:
  imports:
    - pysd
    - pysd.cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/SDXorg/pysd
  summary: System Dynamics Modeling in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://pysd.readthedocs.io/
  dev_url: https://github.com/SDXorg/pysd

extra:
  recipe-maintainers:
    - enekomartinmartinez
    - JamesPHoughton
